---
abstract: 'SideBySide Ticket View for RT'
author:
  - 'Torsten Brumm http://technik.picturepunxx.de/ <tbrumm@mac.com>'
  - 'Christian Loos <cloos@netsandbox.de>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-SideBySideView
no_index:
  directory:
    - html
    - inc
requires:
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tbrumm/RT-Extension-SideBySideView
version: '1.00'
x_module_install_rtx_version: '0.37'
x_requires_rt: 4.0.0
x_rt_too_new: 4.4.0
